
syn keyword cType cl_string_t cl_stringlist_t cl_cfg_file_t cl_cfg_section_t cl_cfg_key_t cl_json_t cl_datetime_t cl_timeout_t cl_thread_t cl_timer_t cl_timer_info_t cl_timer_arg_t cl_chat_t cl_list_entry_t cl_event_t cl_object_t cl_spec_t cl_counter_t cl_plugin_t cl_plugin_info_t cl_log_t cl_list_t cl_list_node_t cl_image_t cl_stack_t cl_stack_node_t cl_queue_t cl_queue_node_t cl_caption_t cl_hashtable_t cl_cqueue_t cl_cstack_t

syn keyword cConstant CL_VOID CL_CHAR CL_UCHAR CL_INT CL_UINT CL_SINT CL_USINT CL_FLOAT CL_DOUBLE CL_LONG CL_ULONG CL_LLONG CL_ULLONG CL_POINTER CL_STRING CL_BOOLEAN CL_CSTRING

